name: Tests

on: [ push, pull_request ]

jobs:
  unit-benchmark-test:
    strategy:
      matrix:
        go: [ "1.21", "1.22", "1.23" ]
        os: [ X64, ARM64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true # don't use cache for self-hosted runners

       # block scenario, comment temporarily
#      - uses: actions/cache@v3
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-

      - name: Unit Test
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Unit Test V2
        run: cd v2 && go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Lint V2
        run: |
            cd v2 
            go vet -stdmethods=false $(go list ./...)
            go install mvdan.cc/gofumpt@v0.2.0
            test -z "$(gofumpt -l -extra .)"

      - name: Benchmark
        run: go test -bench=. -benchmem -run=none ./...
